### ISSUE TITLE
Sidecar EnvFileARN causing ValidationError

### ISSUE THREAD

**Issue by benjaminpottier** [aws/copilot-cli#4821] opened 2023-05-01 17:41 UTC
We just updated copilot cli in our pipeline and it started to throw the following error:

```
ValidationError: Template format error: Parameter name datadog-agentEnvFileARN is non alphanumeric.
```

This is what our sidecar looks like:

```
sidecars:
  datadog-agent:
    image: public.ecr.aws/datadog/agent:latest
    variables:
      ECS_FARGATE: true
      DD_APM_ENABLED: true
    secrets:
      DD_API_KEY: /path/to/secret
```

For now, we've just commented out the sidecar from the manifest in order to get back to deploying. Any idea?

**Comment by efekarakus** [comment] 2023-05-01 17:48
Hi Ben! 

This issue seems to be the same as https://github.com/aws/copilot-cli/issues/4708 where unfortunately we introduced a regression but then fixed the issue here: https://github.com/aws/copilot-cli/commit/67db7a2d4f94c69c836586f714341e587b1b8220, it will go out in the next release.

In the meantime, you can mitigate the issue by renaming `datadog-agent` to `datadogagent` (remove the `'-'`) and hopefully that will unblock you!

**Comment by benjaminpottier** [comment] 2023-05-01 17:51
> Hi Ben!
> 
> This issue seems to be the same as #4708 where unfortunately we introduced a regression but then fixed the issue here: [67db7a2](https://github.com/aws/copilot-cli/commit/67db7a2d4f94c69c836586f714341e587b1b8220), it will go out in the next release.
> 
> In the meantime, you can mitigate the issue by renaming `datadog-agent` to `datadogagent` (remove the `'-'`) and hopefully that will unblock you!

Thank you! Sorry I tried looking if someone already created an issue and didn't notice that.

**Comment by efekarakus** [comment] 2023-05-01 18:32
oh no worries at all! Thanks for understanding, hopefully that resolves the issue :)

**Comment by efekarakus** [comment] 2023-05-08 16:37
Resolving the issue, hope the workaround above mitigated the problem.

**Closed as completed by efekarakus** 2023-05-08 16:37 UTC
Labels: guidance
