### ISSUE TITLE
Resource creation cancelled

### ISSUE THREAD

**Issue by errrken** [aws/copilot-cli#3197] opened 2022-01-20 09:13 UTC
Hi,

We have an app already in a Fargate cluster that we have created manually, years ago.

We now want to try to use copilot instead, so we want to deploy an application and gradually migrate to this one.

However we get the below issue when trying to init the environment. We use the same region as our current application (and we cannot use another region) and also select "Default environment configuration". Any ideas?

```
- Creating the infrastructure for the abc-test environment.                [rollback complete]  [177.4s]
  The following resource(s) failed to create: [InternetGateway, PublicSu                                  
  bnet2, CloudformationExecutionRole, PrivateSubnet2, PublicRouteTable].                                  
   Rollback requested by user.                                                                            
  - An IAM Role for AWS CloudFormation to manage resources                           [delete skipped]     [2.8s]
    Resource creation cancelled                                                                           
  - An ECS cluster to group your services                                            [delete complete]    [2.2s]
  - An IAM Role to describe resources in your environment                            [not started]         
  - A security group to allow your containers to talk to each other                  [not started]         
  - An Internet Gateway to connect to the public internet                            [delete complete]    [2.2s]
    Resource creation cancelled                                                                           
  - Private subnet 1 for resources with no internet access                           [not started]         
  - Private subnet 2 for resources with no internet access                           [delete complete]    [0.0s]
    Template error: Fn::Select  cannot select nonexistent value at index 1                                
                                                                                                          
  - Public subnet 1 for resources that can access the internet                       [not started]         
  - Public subnet 2 for resources that can access the internet                       [delete complete]    [0.0s]
    Template error: Fn::Select  cannot select nonexistent value at index 1                                
                                                                                                          
  - A Virtual Private Cloud to control networking of your AWS resources              [delete complete]    [0.0s]
✘ stack abc-test did not complete successfully and exited with status ROLLBACK_COMPLETE
```

**Comment by efekarakus** [comment] 2022-01-20 11:19
Hi @errrken 👋 

Thanks for the detailed issue description! Which region is this being deployed to? 
It looks like for some reason the availability zone returned from `GetAZs` is invalid: 
https://github.com/aws/copilot-cli/blob/dea26599f8ec029c3d205bc72f4ee4ab36bc1847/e2e/customized-env/vpc.yml#L50

I believe a similar issue happened in the past to a user in our Gitter channel: https://gitter.im/aws/copilot-cli?at=61aea2a976e3791755241692

The root cause was that the default VPC that already existed in the account only had one availability zone. The issue was fixed by the user manually creating a second AZ for the default VPC in the account. 

Here is a link for the customer support info that mentions how to fix it: https://github.com/widdix/aws-cf-templates/issues/37#issuecomment-261269729

**Comment by errrken** [comment] 2022-01-20 13:34
Hi @efekarakus 

Thanks for quick reply, it looks like that solved it!

**Closed as completed** 2022-01-20 13:34 UTC
Labels: guidance
