### ISSUE TITLE
Integrate Copilot with Bamboo

### ISSUE THREAD

**Issue by gopalc-cap** [aws/copilot-cli#1693] opened 2020-11-17 20:08 UTC
ne of our requirement is :Integrate Copilot with Bamboo to build and deploy docker images on AWS seamlessly. Developers do not execute Copilot CLI in given restricted environment. Need detailed information and steps how to perform Copilot integration with Bamboo builds

**Comment by efekarakus** [comment] 2020-11-18 23:42
Heya @gopalc-cap! We replied to the issue here: https://github.com/aws/copilot-cli/issues/1680#issuecomment-728285739 let me know if that doesn't work for you. 

I'll close this issue as a duplicate of #1680

**Closed as completed by efekarakus** 2020-11-18 23:42 UTC
