### ISSUE TITLE
Failed to grant DNS permissions to account

### ISSUE THREAD

**Issue by afgallo** [aws/copilot-cli#2554] opened 2021-07-05 04:03 UTC
Hi,

I've run the command below using an account named **sharedsvc** with the same aws profile name.

```
copilot app init xxx --domain xxx..com --resource-tags application=xxx
```

The first bits of the infra stack has been successfully created by copilot. I've then run the following command specifying a different aws profile named **dev**:

```
copilot env init --name dev --app xxx --profile dev --region ap-southeast-2 --default-config
```

This gives me the error below:

> Sharing DNS permissions for this application to account xxx. ✘ Failed to grant DNS permissions to account xxx.
> 
> ✘ granting DNS permissions: updating application to allow DNS delegation: wait until stack xxx-infrastructure-roles update is complete: ResourceNotReady: failed waiting for successful resource state

CloudFormation logs gives the additional information below:

> Invalid principal in policy: "AWS":"arn:${AWS::Partition}:iam::xxxxxxx:root" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 156b59cb-bb4b-461f-bfa8-a10081ce0997; Proxy: null)

I've checked **sharedsvc** permissions and it has AdministratorAccess to both **sharedsvc** and **dev**. By the way, these accounts have been setup using AWS Control Tower. I use aws access keys and secrets provided by AWS SSO to run copilot commands.

What I am doing wrong?

**Comment by afgallo** [comment] 2021-07-06 01:50
It seems to me the issue is related to this line and the partition parameter is not being replaced correctly @efekarakus ?
https://github.com/aws/copilot-cli/blob/77983421537d9f34575655ab8cba309f30610f33/templates/app/versions/v1.0.1/app.yml#L106

**Comment by iamhopaul123** [comment] 2021-07-06 16:36
Hello @afgallo it seems like this maybe this principle was malformed https://github.com/aws/copilot-cli/blob/77983421537d9f34575655ab8cba309f30610f33/templates/app/versions/v1.0.1/app.yml#L119-L127. Could you help me to check what value you got for this parameter `AppDNSDelegatedAccounts`? Thank you!

**Comment by afgallo** [comment] 2021-07-06 21:25
Hey @iamhopaul123, I got the account number for **sharedsvc** . Would that be correct?

**Comment by iamhopaul123** [comment] 2021-07-06 23:29
> Hey @iamhopaul123, I got the account number for sharedsvc . Would that be correct?

Yes that sounds correct. I am able to reproduce the bug. Looking into it. Thank you so much for reporting the issue!

**Comment by iamhopaul123** [comment] 2021-07-07 18:00
Hello @afgallo. Seems like it is a bug introduced in our latest version. Your suspicion was correct! It is because any function is not permitted within the delimiter of `Fn::Join` and that's the reason why the partition parameter is not rendered correctly. We are working on a fix now and will be included in our next release. Sorry again for this churn.

**Closed as completed** 2021-07-07 21:11 UTC
Labels: type/bug, area/app

**Comment by afgallo** [comment] 2021-07-07 21:20
> Hello @afgallo. Seems like it is a bug introduced in our latest version. Your suspicion was correct! It is because any function is not permitted within the delimiter of `Fn::Join` and that's the reason why the partition parameter is not rendered correctly. We are working on a fix now and will be included in our next release. Sorry again for this churn.

Thanks for fixing it so quickly, @iamhopaul123 👍🏻

**Comment by iamhopaul123** [comment] 2021-07-08 22:35
Hey @afgallo. This is now released 🎉  https://github.com/aws/copilot-cli/releases/tag/v1.8.3

**Comment by afgallo** [comment] 2021-07-08 23:26
> Hey @afgallo. This is now released 🎉 https://github.com/aws/copilot-cli/releases/tag/v1.8.3

Amazing, thanks @iamhopaul123. Will give it a try today! Thanks for all the work you and the team are doing on copilot!
