### ISSUE TITLE
Single pipeline for Application deployment

### ISSUE THREAD

**Issue by avvaidya-aws** [aws/copilot-cli#1710] opened 2020-11-20 19:10 UTC
cross regions (Including China) spread across multi AWS accounts i.e. Single Pipeline which can create environment for dev, stage, prod, DR… in different AWS regions provisioned under different AWS accounts.

**Comment by efekarakus** [comment] 2020-11-20 19:47
Duplicate of #1709

**Closed as completed by efekarakus** 2020-11-20 19:47 UTC
