### ISSUE TITLE
ValidationError: Template error: resource InternalWorkloadsHostedZone does not support attribute type Id in Fn::GetAtt

### ISSUE THREAD

**Issue by comdaze** [aws/copilot-cli#3977] opened 2022-09-03 11:54 UTC
copilot version: 1.21.0 and 1.21.1
AWS Region: **cn-northwest-1**
Demo APP:
https://docs.aws.amazon.com/zh_cn/AmazonECS/latest/developerguide/getting-started-aws-copilot-cli.html

Process and Error：
$ git clone https://github.com/aws-samples/amazon-ecs-cli-sample-app.git demo-app

$ cd demo-app/
$ ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  Dockerfile  index.html  LICENSE  README.md
$ copilot init
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with a containerized application on AWS. An application is a collection of
containerized services that operate together.

Workload type: Load Balanced Web Service
Service name: demo
Dockerfile: ./Dockerfile
parse EXPOSE: no EXPOSE statements in Dockerfile ./Dockerfile
Port: 80
Ok great, we'll set up a Load Balanced Web Service named demo in application test listening on port 80.

✔ Proposing infrastructure changes for stack test-infrastructure-roles
- Creating the infrastructure for stack test-infrastructure-roles                               [create complete]  [31.0s]
  - A StackSet admin role assumed by CloudFormation to manage regional stacks                   [create complete]  [9.9s]
  - An IAM role assumed by the admin role to create ECR repositories, KMS keys, and S3 buckets  [create complete]  [12.5s]
✔ The directory copilot will hold service manifests for application test.

✔ Wrote the manifest for service demo at ../copilot/demo/manifest.yml
Your manifest contains configurations like your container size and port (:80).

✔ Created ECR repositories for service demo.

All right, you're all set for local development.
Deploy: Yes

✔ Manifest file for environment test already exists at ../copilot/environments/test/manifest.yml, skipping writing it.
✔ Linked account 456370280007 and region cn-northwest-1 to application test.

✔ Proposing infrastructure changes for the test-test environment.
- Creating the infrastructure for the test-test environment.  [create complete]  [32.5s]
  - An IAM Role for AWS CloudFormation to manage resources    [create complete]  [11.9s]
  - An IAM Role to describe resources in your environment     [create complete]  [11.6s]
✔ Provisioned bootstrap resources for environment test in region cn-northwest-1 under application test.
✔ Provisioned bootstrap resources for environment test.
✔ Proposing infrastructure changes for the test-test environment.
✘ deploy environment test: check if changeset is empty: create change set copilot-bc6a4f6f-026c-4945-9702-2b85776f7949 for stack test-test: ValidationError: Template error: resource InternalWorkloadsHostedZone does not support attribute type Id in Fn::GetAtt
        status code: 400, request id: 9779d95f-f574-48a7-a44e-7f7e03378dff: describe change set copilot-bc6a4f6f-026c-4945-9702-2b85776f7949 for stack test-test: ChangeSetNotFound: ChangeSet [copilot-bc6a4f6f-026c-4945-9702-2b85776f7949] does not exist
        status code: 404, request id: a0e077f9-0a41-4e0d-8de8-6ebda017b3ea

**Comment by Lou1415926** [comment] 2022-09-06 23:09
Hello @comdaze ! This is weird - I haven't been able to reproduce the issue in us-east-1. It is possible that in the template validation endpoint for `aws-cn` partition does not acknowledge `.Id` attribute for a Route53 Hosted Zone. I will verify and get back to you. Thanks for reporting the issue!

**Comment by jamestupper** [comment] 2022-09-07 22:40
I'm seeing this after running a `copilot init` and selecting `Load Balanced Web Service`. let me know if you want more information that may help repro.

i have a feeling that the output `InternalWorkloadsHostedZone` located [here](https://github.com/aws/copilot-cli/blob/df4dcb91ac9420eda5978c21d5eab24078a11fb2/internal/pkg/template/templates/environment/cf.yml#L664) is clashing with the actual `InternalWorkloadsHostedZone` resource [here](https://github.com/aws/copilot-cli/blob/df4dcb91ac9420eda5978c21d5eab24078a11fb2/internal/pkg/template/templates/environment/cf.yml#L447)

**Comment by Lou1415926** [comment] 2022-09-07 22:59
@jamestupper Ah interesting - that does sounds like a possibility. To help me reproduce the issue - are you using preexisting manifest for that LBWS, or were you letting Copilot generate a new one for you during `copilot init` ?

**Comment by jamestupper** [comment] 2022-09-07 23:00
i'm letting copilot generate a new one for me. the only existing piece i had was a `Dockerfile`

**Comment by Lou1415926** [comment] 2022-09-08 18:18
@jamestupper Thank you for confirming! I am still not able to reproduce this problem :(  I assume the environment manifest is a new piece as well? What is the output if you run  `copilot version` and what is your region?

**Comment by jamestupper** [comment] 2022-09-08 19:55
@Lou1415926 no problem.
copilot version: `v1.21.1`
region: `us-gov-west-1`

**Comment by jamestupper** [comment] 2022-09-10 15:04
@Lou1415926 this scenario works with `v1.19.0`. going to use that version until this is fixed.

**Comment by iamhopaul123** [comment] 2022-09-12 18:52
Hello @jamesiri @comdaze. Based on our tests it seems like `!GetAtt xxx.Id` is not supported in gov cloud or china partition for resource `aws::routet53::hostedzone` (not clearly documented tho). A quick fix would be just use `!Ref` instead. Will send out a quick fix for this. Thank you again for reporting this issue.

**Comment by jamestupper** [comment] 2022-09-12 18:53
awesome - thanks @iamhopaul123!

**Closed as completed** 2022-09-12 19:38 UTC

**Comment by dannyrandall** [comment] 2022-09-27 22:14
Hey all - we just released Copilot v1.22 with this fix! Let us know if you still see any issues!

Blog post: https://aws.github.io/copilot-cli/blogs/release-v122/
Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.22.0
