### ISSUE TITLE
pipeline: POST_BUILD failed when listing service cfn templates

### ISSUE THREAD

**Issue by huezo89** [aws/copilot-cli#1379] opened 2020-09-13 23:48 UTC
When I push the a change to git

Everything seems to be running fine until it reaches 
"Running command ls -lah ./infrastructure"

it says "ls: cannot access ./infrastructure: No such file or directory".

**Comment by huezo89** [comment] 2020-09-14 16:04
Missclicked and closed it.

**Comment by efekarakus** [comment] 2020-09-14 20:18
heya @huezo89 !

Which version of Copilot are you using?

Would you mind printing the rough directory structure of your git repository? I want to make sure that a `copilot/` directory exists with service manifests and `.workspace` file underneath it.
For example:
```
$ tree -a
.
├── admin
│   ├── Dockerfile
|   └── index.js
├── api
|   ├── index.js
│   └── Dockerfile
├── copilot
│   ├── .workspace
│   ├── buildspec.yml
│   ├── pipeline.yml
│   ├── admin
│   │   └── manifest.yml
│   ├── api
│   │   └── manifest.yml
```

**Comment by huezo89** [comment] 2020-09-14 23:47
Thanks for the reply. Here is the image of the directory structure

![image](https://user-images.githubusercontent.com/10298986/93148855-cc8e3880-f6a9-11ea-91a1-e54c8063bb7c.png)

**Comment by efekarakus** [comment] 2020-09-15 00:01
Your directory structure looks good to me! hmmm 🤔 

What happens when you run the following locally?
1. `copilot svc package --output-dir infrastructure/` Do you see an `infrastructure` directory generated with a cloudformation template in it?
2. What's the output of `copilot svc ls --local --json`?
3. What's the output of `copilot env ls --json`?

These are the steps that we take within the buildspec before running `ls -lah ./infrastructure`

**Comment by sinedie** [comment] 2020-12-21 07:31
Hey there, I got the same trouble.

When trying to run `copilot svc package --output-dir infrastructure/` I found out that you need to push `.workspace` file to git otherwise you will have the next error:

`could not find an application attached to this workspace, please run `app init` first`

That solves the issue.

I pushed the `manifest.yml` too, idk if thats a good idea? any advice? Ty.

**Comment by sinedie** [comment] 2020-12-21 18:12
After this, im having another issue... The build reach till

>   docker build -t $workload:$tag $build_args-f $df_path $df_dir_path;
>   image_id=$(docker images -q $workload:$tag);
> done;
>  exit status 1
> [Container] 2020/12/21 17:43:09 Phase complete: POST_BUILD State: FAILED
> [Container] 2020/12/21 17:43:09 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: for workload in $WORKLOADS; do

Maybe caused by:
> Step 1/18 : FROM node:alpine As build
> toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

But I haven't pull 100 times in 6 hours and my other pipeline services works.
This one has something different: uses a build preprocess where generates an static SPA and copies to final image where is served by a node-express server

```

FROM node:alpine As build
...

FROM node:alpine

# Static SPA
COPY --from=build /src/dist /app/dist

...
```

**Comment by efekarakus** [comment] 2020-12-21 19:57
Heya @sinedie ! 

> I found out that you need to push .workspace file to git otherwise you will have the next error

Thanks for finding this out!

> I pushed the manifest.yml too, idk if thats a good idea? any advice? Ty.

Yes, that's definitely a good idea. The `manifest.yml` is meant to be infra-as-code that can be code reviewed by other teammates so it's def. okay to push that to your repository.

> Step 1/18 : FROM node:alpine As build
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: 

:( this is one way that you can mitigate this issue:
https://github.com/copilot-example-voting-app/api/commit/7834a2c66cbb59744229f10a3ee1681b103ad8d6

In the sample code above, I've modified the `buildspec.yml` file to read my docker creds from SSM Parameter Store (see https://docs.aws.amazon.com/systems-manager/latest/userguide/param-create-cli.html#param-create-cli-securestring) (this is free btw). And then added a `docker login` instruction as one of the first steps.

Hope this helps!

**Comment by anup466** [comment] 2021-08-31 10:59
Thanks Huanjani.. i got that issue fixed (ls -lh ./infrastructure file not found).. while running the manual command(copilot svc package --output-dir infrastructure/)  and pushing infra files and manifest to git repo.

Post that it failed due to unable to get image id locally.
_Running command: docker build -t apprunner-svc:pipeline-app-runner-copilotAppRunner-BuildProject-97fa0807-0cfb-4061-9109-ca0339e79b2e -f Dockerfile .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /codebuild/output/src895329424/src/Dockerfile: no such file or directory
Image ID:
repo:308052719878.dkr.ecr.us-east-1.amazonaws.com/app-runner/apprunner-svc:pipeline-app-runner-copilotAppRunner-BuildProject-97fa0807-0cfb-4061-9109-ca0339e79b2e
Region:us-east-1
Phase complete: POST_BUILD State: FAILED
/codebuild/output/tmp/script.sh: line 54: Login: command not found
"docker tag" requires exactly 2 arguments.
See 'docker tag --help'.

Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
The push refers to repository [308052719878.dkr.ecr.us-east-1.amazonaws.com/app-runner/apprunner-svc]
An image does not exist locally with the tag: 308052719878.dkr.ecr.us-east-1.amazonaws.com/app-runner/apprunner-svc_

[Container] 2021/08/31 19:14:17 Phase context status code: COMMAND_EXECUTION_ERROR Message:__ **Error while executing command: for workload in $WORKLOADS; do**

Above one seems known error.. **@efekarakus,  can you please further suggest..**

**Tried below option too..**   
Modify  the buildspec.yml file to read my docker creds from SSM Parameter Store (see https://docs.aws.amazon.com/systems-manager/latest/userguide/param-create-cli.html#param-create-cli-securestring) (this is free btw). And then added a docker login instruction as one of the first steps 
**_But seems it failed with DOCKER_PASSWD not found.._**

**Comment by anup466** [comment] 2021-09-03 14:00
I  got this issue resolved, please close this ticket..
Thanks  @huanjani  for this forum..

**Closed as completed** 2021-12-07 20:43 UTC
Labels: type/bug, area/pipeline
