### ISSUE TITLE
copilot status/show errors

### ISSUE THREAD

**Issue by ssccio** [aws/copilot-cli#5147] opened 2023-07-31 19:09 UTC
In the past couple of weeks, we have had two separate projects start giving errors like the following:

`% copilot svc status --app cms --name email-worker --env prod
✘ describe status of service email-worker: get ECS service description for email-worker: more than one ECS service with tags "copilot-application"="cms","copilot-environment"="prod","copilot-service"="email-worker"`

or 

`% copilot svc show --app cms --name email-worker
✘ describe service email-worker: retrieve rollback alarm names: get service email-worker: more than one ECS service with tags "copilot-application"="cms","copilot-environment"="prod","copilot-service"="email-worker"`

The only thing we have found to be different with these services are the presence of old inactive task definitions, either from updating the service, or deleting and redeploying.

Deleting the old task definitions seems to be a workaround for the issue, but it is extremely time consuming.

**Comment by dannyrandall** [comment] 2023-07-31 19:15
Hey @ssccio, thanks for reporting this.😊 Looks like a duplicate of https://github.com/aws/copilot-cli/issues/5144, which has been resolved by https://github.com/aws/copilot-cli/pull/5125! We're doing a patch release soon - I'll let you know when we release it!

**Closed as completed by dannyrandall** 2023-07-31 19:15 UTC
Labels: type/bug

**Comment by dannyrandall** [comment] 2023-08-02 18:31
Hey @ssccio! This fix has been released in [v1.29.1](https://github.com/aws/copilot-cli/releases/tag/v1.29.1)!🚀🎉

**Comment by ssccio** [comment] 2023-08-03 17:26
Thanks @dannyrandall!
