### ISSUE TITLE
Rest API support

### ISSUE THREAD

**Issue by vikasgoel76** [aws/copilot-cli#1699] opened 2020-11-18 14:53 UTC
Copilot does not provide RestAPI support for integrating with custom DevOps tools

**Comment by efekarakus** [comment] 2020-11-18 23:53
Heya @vikasgoel76 ! This is a duplicate of #1642, let us know if you have something else in mind but the short answer is that with Copilot you can provide flags to automate your process instead of using the default guided walkthrough wizard.

**Closed as completed by efekarakus** 2020-11-18 23:53 UTC
